// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}
