// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function ConnectVPN(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectVPN'](arg1, arg2, arg3);
}

export function DisconnectVPN() {
  return window['go']['main']['App']['DisconnectVPN']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetVPNStatus() {
  return window['go']['main']['App']['GetVPNStatus']();
}
