// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1:string):Promise<{[key: string]: any}>;

export function ConnectVPN(arg1:string,arg2:number,arg3:string):Promise<{[key: string]: any}>;

export function DisconnectVPN():Promise<{[key: string]: any}>;

export function GetLicenseInfo():Promise<{[key: string]: any}>;

export function GetVPNStatus():Promise<{[key: string]: any}>;
