// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetLicenseInfo():Promise<{[key: string]: any}>;

export function GetLicenseStatus():Promise<boolean>;

export function GetStats():Promise<{[key: string]: any}>;

export function GetStatus():Promise<boolean>;
